x-lagoon-project:
  &lagoon-project drupal-open-future-manifesto

x-environment:
  &default-environment
  LAGOON_PROJECT: *lagoon-project
  LAGOON_ROUTE: http://drupal-open-future-manifesto.docker.amazee.io
  NODE_ENV: development
  HOSTNAME: 0.0.0.0
  PORT: '3000'
  POSTGRES_DB: ${POSTGRES_DB:-manifesto}
  POSTGRES_USER: ${POSTGRES_USER:-manifesto}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-manifesto}
  DATABASE_URL: postgresql://${POSTGRES_USER:-manifesto}:${POSTGRES_PASSWORD:-manifesto}@postgres:5432/${POSTGRES_DB:-manifesto}?schema=public

x-user:
  &default-user
  user: '1000'

services:
  node:
    << : [*default-user]
    build:
      context: .
      dockerfile: lagoon/node.dockerfile
    command: /bin/sh /app/lagoon/scripts/next-dev.sh
    depends_on:
      postgres:
        condition: service_healthy
    environment: *default-environment
    networks:
      - amazeeio-network
      - default
    labels:
      lagoon.type: node
    ports:
      - '3000:3000'
    volumes:
      - .:/app:delegated

  postgres:
    image: uselagoon/postgres-16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-manifesto}
      POSTGRES_USER: ${POSTGRES_USER:-manifesto}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-manifesto}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-manifesto} -d ${POSTGRES_DB:-manifesto}']
      interval: 5s
      timeout: 5s
      retries: 10
    labels:
      lagoon.type: postgres
      lagoon.autogeneratedroute: 'false'
    networks:
      - amazeeio-network
      - default
    ports:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  amazeeio-network:
    external: true